# Generated by Django 4.0.2 on 2022-11-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSetup', '0004_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table=None,
        ),
    ]
