# Generated by Django 4.0.2 on 2022-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSetup', '0010_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
