# Generated by Django 4.0.2 on 2022-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSetup', '0012_test_delete_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
