# Generated by Django 4.0.2 on 2022-11-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSetup', '0013_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
